### ISSUE TITLE
Store Photos in Aptible EC2 until a near-future release

### ISSUE THREAD

**Issue by robertnix** [DxRx/dxrx-aud#123]

**Comment by awatson1978** [comment]
Ug.  Was hoping that we would be able to use S3.  I'll look through my notes on what solutions are available for EC2.

**Comment by robertnix** [comment]
The purpose of each of these moves to the backlog is to reduce the work
needed for MVP.

I thought that EC2 essentially uses the native Linux file system within an
encrypted container.  So anything that works on your Mac in a server-side
role would work there.

S3, on the other hand, is a tuple store so we'd need to use a specific API
and do our own server-side encryption for compliance purposes.   We also
need a BAA with Amazon, as S3 is not a bundled part of the Aptible service.

S3 seemed like more work, and if we could put that off for a few months
we'd have less work to do for the MVP.

Do you think that S3 is not more work than EC2?

**Comment by awatson1978** [comment]
Mmmm...  well, S3 is a HIPAA eligible service, which means - as I understand it - that it's running on a Linux OS that has operating system level encryption and user accounts.

https://blogs.aws.amazon.com/security/post/Tx3FDPNNKZ5XFEE/Frequently-Asked-Questions-About-HIPAA-Compliance-in-the-AWS-Cloud-Part-Two 

The photos that we're taking are de-identified; and while one could argue that a palmprint is a biometric signature, the counter argument is that there's no global register of palmprints, since the standard is fingerprints; and the HIPAA deidentification rules specify full face photographs, not any photograph.  So, I tend to think of the medication adherence photos as being fairly low risk of being able to identify an individual in the case of a leak; and therefore not needing encryption-at-rest, and being fine with operating system level encryption.

Lastly, there's a pretty robust package called [edgee:slingshot](https://atmospherejs.com/edgee/slingshot) which bypasses the server altogether, and loads an image from the browser directly to S3.  

That seems like the simplest way to handle the photos to me.  Get the BAA in place, load directly from browser to S3 using a well known established library, and have a good policy in place that the only photos we store in S3 are pictures of pills in hands, and no full-face photos are allowed to be stored using this manner.

**Comment by robertnix** [comment]
The process you describe would not be HIPAA compliant.  You're basically
arguing that no one should care about photos of hands, but I don't want to
set us up for a NY Times article about our improperly handling a 1,000,000
photos of alcoholics.

**Comment by awatson1978** [comment]
:shrug:  We had such processes at NY Methodist Hospital.  Your call.  If you're uncomfortable with that risk profile, then we have to set up the EC2 instance, which will take considerably longer (in my opinion).

**Comment by awatson1978** [comment]
http://stackoverflow.com/documentation/meteor/3119/file-uploading#t=201610172033370995858

**Comment by awatson1978** [comment]
This issue was moved to DxRx/com.dxrxmedical.treatalcohol#21
