### ISSUE TITLE
Add CORS <meta> tag

### ISSUE THREAD

**Issue by awatson1978** [DxRx/dxrx-aud#75]
http://github.com/meteor/meteor/issues/7772

**Comment by robertnix** [comment]
Fixed by cordova-plugin-bactrack 56c5b8a.

This turned out to be a pain.  IOS10 requires that ws: and wss: be added to the app's Content-Security-Policy, but a bad Content Security Policy is wired in to the old revs of the meteor-tool and various Cordova plugins.  To work around this, we rewrite these rules by editing them in the source code ~/.meteor (3 places), and the Cordova plugins after they are installed during build time.  Gross, but it works with a narrowly scoped searching pattern which can be seen in cordova-plugin-bactrack's fix-csp-bug.sh script.
